openapi: 3.0.3
info:
  title: Budget management API
  description: Budget management API
  version: 1.0.0
servers:
  - url: 'https://d5dgrt4l9npeppp5ef61.apigw.yandexcloud.net'
paths:
  /user:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4ef0fpk7mql64fb9g2i
      operationId: getUserById
      parameters:
        - explode: true
          in: query
          name: id
          required: true
          schema:
            description: user id
            type: string
          style: form
      responses:
        '200':
          description: Success response
        '400':
          description: Server error
        '404':
          description: User with id not found
      summary: get user by id
    post:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4ef0fpk7mql64fb9g2i
      operationId: createUser
      responses:
        '200':
          description: Success response
        '400':
          description: Server error
      summary: create new user
    put:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4ef0fpk7mql64fb9g2i
      operationId: updateUser
      responses:
        '200':
          description: Success response
        '400':
          description: Server error
        '404':
          description: User not found
      summary: update budget
    delete:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4ef0fpk7mql64fb9g2i
      operationId: deleteUserById
      parameters:
        - explode: true
          in: query
          name: id
          required: true
          schema:
            description: user id
            type: string
          style: form
      responses:
        '200':
          description: Success response
        '400':
          description: Server error
        '404':
          description: User with id not found
      summary: delete user by id
  /budget/{id}:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4e6a72hp7187il17v2p
      operationId: getBudgetById
      parameters:
        - in: path
          name: id
          required: false
          schema:
            description: budget id
            type: string
      responses:
        '200':
          description: Success response
        '400':
          description: Server error
        '404':
          description: Budget with id not found
      summary: get budget by id
  /budget:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4e6a72hp7187il17v2p
      operationId: getBudgetsByUserId
      parameters:
        - in: query
          name: userId
          required: false
          schema:
            description: user id
            type: string
          style: form
      responses:
        '200':
          description: Success response
        '400':
          description: Server error
        '404':
          description: Budget with id not found
      summary: get budget by id
    post:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4e6a72hp7187il17v2p
      operationId: createBudget
      responses:
        '200':
          description: Success response
        '400':
          description: Server error
      summary: create new budget
    put:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4e6a72hp7187il17v2p
      operationId: updateBudget
      responses:
        '200':
          description: Success response
        '400':
          description: Server error
        '404':
          description: Budget not found
      summary: update budget
    delete:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4e6a72hp7187il17v2p
      operationId: deleteBudgetById
      parameters:
        - explode: true
          in: path
          name: id
          required: true
          schema:
            description: user id
            type: string
          style: form
      responses:
        '200':
          description: Success response
        '400':
          description: Server error
        '404':
          description: Budget with id not found
      summary: delete budget by id
x-yc-apigateway:
  service_account: aje4ej9qgr488q4tauai
  
